### ISSUE TITLE
网站打开提示包含恶意软件

### ISSUE THREAD

**Issue by san-na** [csuldw/MachineLearning#1]
http://csuldw.github.io/2016/02/25/2016-02-25-machine-learning-MNIST-dataset/
![](https://ww1.sinaimg.cn/large/006tNc79gy1fdmqgxve11j317s0nsta1.jpg)

**Comment by csuldw** [comment]
你把前面的csuldw.github.io替换成www.csuldw.com就不会报毒，还没搞清楚这个bug哪来的
