### ISSUE TITLE
程序问题

### ISSUE THREAD

**Issue by yhlleo** [csuldw/MachineLearning#3]
楼主发布的 mRMR 代码，与作者发布的代码一样：

http://home.penglab.com/proj/mRMR/

我简单看了一下代码，很多Bug，楼主有运行过吗？

首先是`nrutil.cpp`中的语法错误：

```
void nrerror(error_text)
char error_text[];

...

float *vector(nl,nh)
long nh,nl;

...
```

这样定义和声明函数形参列表？可能我学了假的C语言…

还有 `compute_jointprob()`函数，作者注释掉部分代码，说旧代码slow, 但是新代码好像忘了自己该干嘛吧？

**Comment by csuldw** [comment]
代码是http://home.penglab.com/proj/mRMR/里面的，这里只是介绍了如何使用这个源码的，本人在centos6.5上面运行过，没有报错。之前没有细看源代码，有空我回头看看
